//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication15.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applied
    {
        public string Username { get; set; }
        public string Email { get; set; }
        public string Registeration_Num { get; set; }
        public string Designation { get; set; }
        public string Password { get; set; }
    }
}
